# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: node -v
