# This is a basic workflow to help you get started with Actions

name: Compile android

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Cargmos los secrets
      - name: Test variables y secrets
        run: |
          # create variables
          echo "PWD: "
          pwd
          echo "RUNNER_TEMP:  $RUNNER_TEMP"
          echo "XCode Version:"

      # NODE Y COMPILACION
      